name: docs

on:
 push:
  branches:
    - master
 workflow_dispatch:
 pull_request:
  branches:
    - master

jobs:
  Build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: JuliaPlots/PlotDocs.jl
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v1
      - name: Build documentation
        env:
          PYTHON: ""
          DOCUMENTER_KEY: ${{secrets.DOCUMENTER_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: bash docs/ci_build.sh
